[project]
name = "kv-store"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "itssubhodiproy", email = "subhodiproy281@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "grpcio>=1.83.1",
    "grpcio-tools>=1.83.1",
]

[project.scripts]
kv-store = "kv_store.main:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
