# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kv_store/storage.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'kv_store/storage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16kv_store/storage.proto\x12\x02kv\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"+\n\x0bGetResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\r\n\x05value\x18\x02 \x01(\t\"(\n\nPutRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\r\n\x0bPutResponse\"\x1c\n\rDeleteRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x10\n\x0e\x44\x65leteResponse2\x8a\x01\n\x07Storage\x12&\n\x03Get\x12\x0e.kv.GetRequest\x1a\x0f.kv.GetResponse\x12&\n\x03Put\x12\x0e.kv.PutRequest\x1a\x0f.kv.PutResponse\x12/\n\x06\x44\x65lete\x12\x11.kv.DeleteRequest\x1a\x12.kv.DeleteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kv_store.storage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETREQUEST']._serialized_start=30
  _globals['_GETREQUEST']._serialized_end=55
  _globals['_GETRESPONSE']._serialized_start=57
  _globals['_GETRESPONSE']._serialized_end=100
  _globals['_PUTREQUEST']._serialized_start=102
  _globals['_PUTREQUEST']._serialized_end=142
  _globals['_PUTRESPONSE']._serialized_start=144
  _globals['_PUTRESPONSE']._serialized_end=157
  _globals['_DELETEREQUEST']._serialized_start=159
  _globals['_DELETEREQUEST']._serialized_end=187
  _globals['_DELETERESPONSE']._serialized_start=189
  _globals['_DELETERESPONSE']._serialized_end=205
  _globals['_STORAGE']._serialized_start=208
  _globals['_STORAGE']._serialized_end=346
# @@protoc_insertion_point(module_scope)
